name: CI
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Cache sbt
        uses: coursier/cache-action@v6

      - name: Build and test
        run: sbt test


